# Generated by Django 3.2.13 on 2023-02-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Name slug')),
                ('title', models.CharField(max_length=32, verbose_name='Title Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Name slug')),
                ('title', models.CharField(max_length=32, verbose_name='Title ItemMenu')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_menu', to='treemenu.menu', verbose_name='Parent Menu')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_parent', to='treemenu.itemmenu', verbose_name='Parent ItemMenu')),
            ],
            options={
                'verbose_name': 'ItemMenu',
                'verbose_name_plural': 'ItemMenu',
            },
        ),
    ]
